### PR TITLE
React workflow added

### PR DESCRIPTION
**Pull request by detronetdip**
I have added the workflow for react project.

I have added component, styles, hooks and context workflow.

### CODE REVIEW

**Comment by detronetdip** [comment]
@Onyelaudochukwuka can you please review it?

**Comment by Onyelaudochukwuka** [comment]
> @Onyelaudochukwuka can you please review it?

I'm on that right now 👍🏼

**Comment by Onyelaudochukwuka** [comment]
Every thing seems good so far checking out the template

**Comment by Onyelaudochukwuka** [comment]
This an awesome entry!
I think the section marked below should be removed since they won't be needed
Screen Shot 2022-10-01 at 4 35 19 PM

**Comment by Onyelaudochukwuka** [comment]
If all these are fixed the you got a merge 👍🏼

**Comment by detronetdip** [comment]
In my hactoberfest dashbord this pull request is showing not participating tag I think this is happening because of the hacktoberfest tag. Please allow me to close this pull request so that I can create a new pull request with all the changes.

**Pull request closed without merging**
