### PR TITLE
React workflow added

### PR DESCRIPTION
**Pull request by detronetdip**
solves #3 

I have added workflow for react.

### CODE REVIEW

**Review by Onyelaudochukwuka — COMMENTED** [review]
## Thanks for taking the time to contribute by creating a pull request.
Please hold on while your contributions are being reviewed.
This is an automated message,you'll get a response from a maintainer soon.<p></p>

**Comment by detronetdip** [comment]
@Onyelaudochukwuka I have opened this new pull request with your suggested changes. Please review it.

**Comment by Onyelaudochukwuka** [comment]
Ok on that

**Comment by Onyelaudochukwuka** [comment]
You didn't need to close the previous pull request thou any changes upstream will be reflected after opening

**Comment by Onyelaudochukwuka** [comment]
The template file changes are great

**Comment by Onyelaudochukwuka** [comment]
Let's clear up the last two comments
and we've got a merge

**Comment by detronetdip** [comment]
@Onyelaudochukwuka could not understand what you are saying. please instruct me what should I do now?

**Comment by Onyelaudochukwuka** [comment]
> @Onyelaudochukwuka could not understand what you are saying. please instruct me what should I do now?

do you intend to generate your functions as folder with the function file in it or just as a function file?

**Comment by detronetdip** [comment]
Just as a function file

**Comment by Onyelaudochukwuka** [comment]
> Just as a function file

ooh in that case try using the isFile configuration

**Comment by Onyelaudochukwuka** [comment]
So it's going to be basically the same format as the context block

**Comment by detronetdip** [comment]
I think this time it is fine.

**Comment by Onyelaudochukwuka** [comment]
Thanks for your contributions

**Pull request merged**
